### ISSUE TITLE
DiscoveryService Interface differs from JSON response

### ISSUE THREAD

**Issue by danielbayley80** [digime/digime-sdk-nodejs#107]
this makes key properties inaccessible when using strong types. a work around is to force the service to a type "any".

**Interface:**
```
export interface DiscoveryService {
    id: number;
    name: string;
    serviceGroups: Array<{ id: number }>;
}
```

**JSON response.**
![image](https://user-images.githubusercontent.com/1572154/154851546-be0ef9ea-488f-4469-b907-01654e449042.png)

**Illustration of the issue**
![image](https://user-images.githubusercontent.com/1572154/154851712-f0163768-d824-4992-9014-75b6ec41e56c.png)

**Comment by ogi1982** [comment]
Issue is fixed and will be include in next release (version greater than 8.0.0)
