### ISSUE TITLE
Parameter `state` in `sdk.getAuthorizeUrl` is marked as optional but is actually required

### ISSUE THREAD

**Issue by nicolomaioli** [digime/digime-sdk-nodejs#125]
## Checklist
- [x] I’m using the latest version of the digi.me Private Sharing SDK.
- [x] I'm using the latest version of the digi.me App.
- [x] I've searched for existing [GitHub issues](https://github.com/digime/digime-sdk-nodejs/issues)
- [x] I've looked for existing answers in the [SDK Documentation](https://github.com/digime/digime-sdk-nodejs/blob/master/docs/README.md) and [Developer FAQs](https://digime.freshdesk.com/support/solutions/9000115894)
- [x] This issue does not relate to security and can be disclosed publicly on Github.
## Environment

MacBook Air 2020 Apple M1
Node v18.12.1
Typescript v4.9.4
Next.js v13.1.1

## Goals

Call `sdk.getAuthorizeUrl()` with the parameters specified in the type definitions.

## Expected Results

The call is successful.

## Actual Results

Error: `JWT payload failed JSON schema validation`. If I add the `state` parameter then the call succeeds, but because the parameter is marked as optional it doesn't throw a type error.

## Steps to Reproduce

- Clone the [example](https://github.com/digime/digime-sdk-nodejs-example)
- Open `examples/read-data/index.js`
- Remove the `state` parameter [here](https://github.com/digime/digime-sdk-nodejs-example/blob/master/examples/read-data/index.js#L83)
- Run the application

## Code Samples & Details

```javascript
  let authorizationOptions = {
    contractDetails: CONTRACT_DETAILS,
    callback: `${getOrigin(req)}/error`,
    serviceId: SERVICE_ID,
    state: new URLSearchParams({ userId }).toString(), // <= Remove this parameter
  };

  try {
    const { url, codeVerifier, session } = await sdk.getAuthorizeUrl(authorizationOptions); // <= this call fails

    // Store the codeVerifer against this user to use later.
    if (codeVerifier) {
      saveUserInfo(userId, { codeVerifier, session });
    }

    // Redirect the user to start the authorization process.
    res.redirect(url);
  } catch (e) {
    // tslint:disable-next-line:no-console
    console.error(e.toString());
    res.render("pages/error");
    return;
  }
});
```

**Comment by ogi1982** [comment]
Hi @nicolomaioli, thanks for your detailed reproduction steps. Good catch, state param should be mandatory and we will fix this with next SDK release. This param will not be optional.

**Comment by ogi1982** [comment]
Issue is fixed and will be include in next release (version greater than 8.0.0)
